version: '3.3'
services:
  nginx:
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
  mongo:
    image: mongo:6.0.4
    ports: 
     - '27017:27017'
  backend:
    build: ./backend
    environment:
      WAIT_HOSTS: mongo:27017
  frontend:
    build: ./react-project
    environment:
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
      - WDS_SOCKET_PORT=0