version: '3.3'
services:
  services:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./letsencrypt-site:/usr/share/nginx/html
    networks:
      - docker-network
  mongo:
    image: mongo:6.0.4
    ports:
      - '27017:27017'
  backend:
    build: ./backend
    environment:
      WAIT_HOSTS: mongo:27017
  frontend:
    build: ./react-project
    environment:
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
      - WDS_SOCKET_PORT=0
  networks:
    docker-network:
      driver: bridge
